### ISSUE TITLE
Downloading from NOAA

### ISSUE THREAD

**Issue by hmb1** [icyroadsafety/LCR---vehicle-Loss-of-Control-Risk#1] opened 2022-12-06 11:59 UTC
@icyroadsafety 
I'm having trouble with the ncks command to download data from other models.  Apparently the path is different for each one.  I can't make sense out of how to do it (like for the NAM) and I haven't been able to find examples on the web.   I'd like to eventually generate maps from the HRRR, NAM, 4K NAM (NAM NEST) and possibly others.

Dan which specific products are you having trouble with ?   
Theres  is a 4GB chunking  limit with DAP ? 
Also some of the products Cannot be downloaded with DAP ?

**Comment by icyroadsafety** [comment] 2022-12-07 09:33
I'd like to download the same set of data for each model just like the ncks command for the GFS does.  But it appears the data from the other models is not organized on NOMADS like the data from the GFS.   For example, when I go to the HRRR model folder on NOMADs:

https://nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/hrrr.20221207/conus/

There are multiple grib2 files and folders, and none of them work when I try to ncks them into an nc file like this:

ncks -v tmp2m,dpt2m,rh2m,apcpsfc,cfrzrsfc https://nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/hrrr.20221207/conus/bufrsnd.t00z hrrr20221207_00z.nc

Do those other models require a different ncks command or path, or another method of data importing altogether?  I get this very lengthy error when running the above command:

syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
context: <!DOCTYPE^ HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL /pub/data/nccf/com/hrrr/prod/hrrr.20221207/conus/bufrsnd.t00z.dds was not found on this server.</p></body></html>
ncks: INFO DAP-access to https://nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/hrrr.20221207/conus/bufrsnd.t00z failed with error code -90. Translation into English with nc_strerror(-90) is "NetCDF: file not found"
ncks: INFO Will now attempt wget on the full filepath. wget will fail if the file is "hidden" behind a DAP server. Unfortunately, failed wget attempts creates rather long pathnames in the current directory. fxm TODO nco970, nco971. On the other hand, wget should succeed if the file is stored in any publicly-accessible web location.
ncks: INFO Unable to find file /nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/hrrr.20221207/conus/bufrsnd.t00z on local system. Found hsi command indicating presence of High Performance Storage System (HPSS). Will assume file is stored on HPSS. Received no local path information and so will try to derive suitable local filepath from given filename...
ncks: INFO Retrieved files will be stored in derived directory ./nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/hrrr.20221207/conus
--2022-12-07 03:29:19--  https://nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/hrrr.20221207/conus/bufrsnd.t00z
Resolving nomads.ncep.noaa.gov (nomads.ncep.noaa.gov)... 23.36.15.136, 23.36.15.224, 23.15.241.196, ...
Connecting to nomads.ncep.noaa.gov (nomads.ncep.noaa.gov)|23.36.15.136|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/hrrr.20221207/conus/bufrsnd.t00z/ [following]
URL transformed to HTTPS due to an HSTS policy
--2022-12-07 03:29:20--  https://nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/hrrr.20221207/conus/bufrsnd.t00z/
Reusing existing connection to nomads.ncep.noaa.gov:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/hrrr.20221207/conus/bufrsnd.t00z’

nomads.ncep.noaa.gov/pub/data     [    <=>                                           ] 162.57K   257KB/s    in 0.6s

2022-12-07 03:29:24 (257 KB/s) - ‘nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/hrrr.20221207/conus/bufrsnd.t00z’ saved [166469]

ERROR: nco__open() unable to open file "nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/hrrr.20221207/conus/bufrsnd.t00z"
ERROR NC_ENOTNC Not a netCDF file
HINT: NC_ENOTNC errors can occur for many reasons. If your use-case matches one of the four listed below, take the corrective action indicated:
1. An NCO operator linked only to the classic netCDF3 library attempts to read netCDF4 (or HDF5) files. However, this executable seems to have been built with the capability to manipulate netCDF4 files, so it is unlikely that this command failed only because the input datasets are netCDF4 format. Something else is going wrong.
2. NCO attempts to read other filetypes (HDF4, HDF-EOS2, PnetCDF/CDF5) for which support must be (but was not) enabled at netCDF build-time. NCO can access HDF4 files if NCO is first re-linked to a version of netCDF configured with the --enable-hdf4 option. This is a non-standard netCDF build option described here: http://www.unidata.ucar.edu/software/netcdf/docs/build_hdf4.html. NCO can access PnetCDF/CDF5 files if NCO is first re-linked to netCDF version 4.4.0 or later.
3. NCO attempts to utilize diskless (i.e., RAM) files.  In this case remove the diskless switches (e.g., --ram or --diskless) and then re-issue the command.
4. Access to a DAP URL fails, and the backup method of downloading the URL using wget obtains a data aggregation file (e.g., a .ncml file) instead of an actual netCDF file. In this case the problem is with the DAP server or URL.
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__open()
nco_err_exit(): ERROR Error code is -51. Translation into English with nc_strerror(-51) is "NetCDF: Unknown file format"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)

**Comment by hmb1** [comment] 2022-12-07 14:10
HI Dan,
 On the nomads home page 
[https://nomads.ncep.noaa.gov/](https://nomads.ncep.noaa.gov/)
If the product has the link "OpenDAP" then follow that link to the  directory view, and then  click the "info"  link, and then select the url  e.g    for HRR this link today is 
[https://nomads.ncep.noaa.gov/dods/hrrr/hrrr20221207/hrrr_sfc.t03z.info](https://nomads.ncep.noaa.gov/dods/hrrr/hrrr20221207/hrrr_sfc.t03z.info)

Use the above link - minus the info suffix in the ncks command e.g  
ncks -v apcpsfc,rh2m  https://nomads.ncep.noaa.gov/dods/hrrr/hrrr20221207/hrrr_sfc.t03z out.nc

If the product on the nomds page doesn't have an OpenDAP link then the  grib files have to be downloaded for each timestamp, converted to  NetCDF and then concatenated together. 

...Henry

**Comment by icyroadsafety** [comment] 2022-12-08 06:55
Thank you, that is what I needed!  I successfully downloaded data from the HRRR and the NAM NEST tonight.  The only problem I ran into is that the HRRR data could not be downloaded in a single step, I received an error when executing the ncks command for all of the LCR-required variables:

ERROR NC_EVARSIZE One or more variable sizes violate format constraints
HINT: NC_EVARSIZE errors occur when attempting to copy or aggregate input files together into an output file that exceeds the per-file capacity of the output file format, 

I had to download each variable into five separate .nc files, then merge them with "cdo merge" after download.  The final file was 2.7GB.

**Comment by icyroadsafety** [comment] 2022-12-08 07:09
I'll mark this issue fixed since the file size issue is manageable.

**Closed as completed by icyroadsafety** 2022-12-08 07:09 UTC

**Comment by hmb1** [comment] 2022-12-08 11:31
FYI   you can merge files with NCO  
~~~
ncks -4  -v apcpsfc https://nomads.ncep.noaa.gov/dods/gfs_0p25/gfs20221207/gfs_0p25_00z  gfs-0p25_00.nc
ncks -4 -v tmp2m https://nomads.ncep.noaa.gov/dods/gfs_0p25/gfs20221207/gfs_0p25_00z  gfs-0p25_00-tmp2m.nc 
tmp2m.nc
~~~

// do merge i.e copy tmp2m to destination
`ncks -A -v tmp2m gfs-0p25_00-tmp2m.nc  gfs-0p25_00.nc`
